### ISSUE TITLE
How do you build this project

### ISSUE THREAD

**Issue by orefalo** [otissv/graphql-guru-ide#1]
I am trying 

⟩npm run build

but it complains about a missing '../../remodule/dist/remodule' folder

Thank you,

will try to add:

* cli starter
* graphql-voyager tab

**Comment by otissv** [comment]
It should be using remoule from npm not local.  I've pushed the changes

**Comment by orefalo** [comment]
Thank you,
unless I missed something ; I am still getting an issue

> react-scripts build

module.js:491
    throw err;
    ^

Error: Cannot find module './util/resolveCommand'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./graphql-guru-ide/node_modules/cross-spawn/lib/parse.js:3:22)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

**Comment by orefalo** [comment]
ok.. so.. you have node_modules under source control.  reactscript not found.. trying to troubleshoot the other issues..

**Comment by otissv** [comment]
Delete the node_modules and the yarn.lock. Not sure why.  .gitignore is not working

**Comment by orefalo** [comment]
expect a pullreq from me

**Comment by otissv** [comment]
cool

**Comment by orefalo** [comment]
.gitignore is not working because files are already under source control. anyway, got it to build - cleaning up
